### PR TITLE
Make internal state of lazydict resilient to error by preserving its state.

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by cameron-white-janrain** [comment]
@Janrain-Colin are you still maintaining this?

**Comment by ticosax** [comment]
@cameron-white-janrain do you know someone (or yourself) ready to take over the project ?
I can volunteer, If I can publish releases to pypi under the same name.

**Comment by ticosax** [comment]
has been rebased.

**Comment by cameron-white-janrain** [comment]
@ticosax There is no plan to turn over ownership to anyone outside of Janrain. Being that LazyDict is not a primary project our response time maybe a bit slow depending what else we are working on. That being said we do use LazyDict internally and are happy receive features and bug requests. However, If you need something done more quickly I suggest that you install from your own branch until we get around to reviewing/merging.

BTW. Thank you very much for your contributions. :+1:

**Comment by ticosax** [comment]
@cameron-white-janrain I was under the impression the project was abandoned.

If it is still alive this is even better. So thank you for this.

**Pull request merged**
